apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: products-binding
  namespace: rabbitmq

spec:
  vhost: shopixy

  source: shopixy.events

  destination: products
  destinationType: queue

  routingKey: products.*

  rabbitmqClusterReference:
    name: rabbitmq
