apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: orders-binding
  namespace: rabbitmq

spec:
  vhost: shopixy

  source: shopixy.events

  destination: orders
  destinationType: queue

  routingKey: orders.*

  rabbitmqClusterReference:
    name: rabbitmq
