apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: shopixy-app
  namespace: rabbitmq

spec:
  vhost: shopixy

  userReference:
    name: shopixy-app

  permissions:
    configure: ".*"
    write: ".*"
    read: ".*"

  rabbitmqClusterReference:
    name: rabbitmq
