apiVersion: v1
kind: Service

metadata:
  name: shopixy-postgres-metrics
  namespace: postgresql

  labels:
    app: shopixy-postgres-metrics

spec:
  selector:
    cnpg.io/cluster: shopixy-postgres
    cnpg.io/podRole: instance

  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
      protocol: TCP
