apiVersion: v1
kind: Secret
metadata:
  name: shopixy-postgres-secret
  namespace: postgresql

type: kubernetes.io/basic-auth

stringData:
  username: "__POSTGRES_USER__"
  password: "__POSTGRES_PASSWORD__"
