apiVersion: 1

groups:
  - orgId: 1
    name: Postgres
    folder: Infrastructure
    interval: 1m

    rules:
      - uid: pgreplicationlagwarn

        title: PostgreSQL Replication Lag Warning

        condition: C

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: ffom74f70o2rkb
            model:
              editorMode: code
              expr: max(cnpg_pg_replication_lag)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A

          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 10
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query

              datasource:
                type: __expr__
                uid: __expr__

              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold

        noDataState: OK
        execErrState: Alerting

        for: 2m

        annotations:
          summary: Replication lag exceeded 10 seconds

        labels:
          severity: warning
          stack: postgres

        isPaused: false

        notification_settings:
          receiver: empty
