apiVersion: 1

groups:
  - orgId: 1
    name: Redis
    folder: Infrastructure
    interval: 1m

    rules:
      - uid: redisrdbsavefailure

        title: Redis RDB Save Failure

        condition: C

        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: ffom74f70o2rkb
            model:
              editorMode: code
              expr: min(redis_rdb_last_bgsave_status)
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              range: false
              refId: A

          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query

              datasource:
                type: __expr__
                uid: __expr__

              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold

        noDataState: Alerting
        execErrState: Alerting

        for: 2m

        annotations:
          summary: Redis RDB background save failed

        labels:
          severity: critical
          stack: redis

        isPaused: false
