apiVersion: v1
kind: Secret
metadata:
  name: mongodb-exporter-secret
  namespace: mongo
type: Opaque
stringData:
  mongodb-uri: "mongodb://mongo-admin:Fadyadel2010%21@mongo-0.mongo-headless.mongo.svc.cluster.local:27017,mongo-1.mongo-headless.mongo.svc.cluster.local:27017,mongo-2.mongo-headless.mongo.svc.cluster.local:27017/admin?authSource=admin&replicaSet=rs0"
