apiVersion: v1
kind: LimitRange

metadata:
  name: {{ service }}-limits
  namespace: {{ namespace }}

spec:
  limits:
    - type: Container

      defaultRequest:
        cpu: {{ default_request_cpu }}
        memory: {{ default_request_memory }}

      default:
        cpu: {{ default_cpu }}
        memory: {{ default_memory }}

      max:
        cpu: {{ max_cpu }}
        memory: {{ max_memory }}

      min:
        cpu: {{ min_cpu }}
        memory: {{ min_memory }}
