apiVersion: v1
kind: Namespace

metadata:
  name: {{ namespace }}

  labels:

    app.kubernetes.io/name: {{ service }}
    app.kubernetes.io/part-of: shopixy-platform
    app.kubernetes.io/managed-by: platform-bootstrap

    platform.shopixy.io/profile: {{ profile }}
    platform.shopixy.io/environment: {{ environment }}

    platform.shopixy.io/service: {{ service }}
    platform.shopixy.io/tier: {{ tier }}
    platform.shopixy.io/criticality: {{ criticality }}

    platform.shopixy.io/backup: {{ backup }}

  annotations:

    platform.shopixy.io/description: "{{ description }}"
    platform.shopixy.io/owner: "Ahram Software"
