#!/bin/bash
set -euo pipefail

export KUBECONFIG=${KUBECONFIG:-$HOME/.kube/config}

# Pass KUBECONFIG explicitly through sudo so it is not lost in the root environment
KUBECTL="sudo -E kubectl --kubeconfig=${KUBECONFIG}"
HELM="sudo -E helm"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "================================="
echo "Shopixy PostgreSQL Bootstrap v2"
echo "================================="
echo ""

############################################
# Generate Configs
############################################

echo "Generating Secrets..."
chmod +x "$SCRIPT_DIR/generate-configs.sh" && sudo bash "$SCRIPT_DIR/generate-configs.sh"
echo ""

############################################
# Install CNPG
############################################

echo "Installing CloudNativePG..."

$HELM repo add cnpg https://cloudnative-pg.github.io/charts 2>/dev/null || true

$HELM repo update

$HELM upgrade --install cnpg \
  cnpg/cloudnative-pg \
  -n cnpg-system \
  --create-namespace \
  --wait

echo ""

############################################
# Wait Operator
############################################

echo "Waiting for CNPG Operator..."

$KUBECTL rollout status \
  deployment/cnpg-cloudnative-pg \
  -n cnpg-system \
  --timeout=300s

echo ""

############################################
# Namespace
############################################

echo "Creating Namespace..."

$KUBECTL apply -f "$SCRIPT_DIR/namespace.yaml"

echo ""

############################################
# Secrets
############################################

echo "Creating Database Secret..."

$KUBECTL apply -f "$SCRIPT_DIR/secret.yaml"

echo ""

echo "Creating MinIO Backup Secret..."

# minio-backup-secret.yaml is not generated by generate-configs.sh, so we
# generate it inline here from env vars. If not exported, prompt interactively.
MINIO_ACCESS_KEY="${MINIO_ACCESS_KEY:-minioadmin}"

if [ -z "${MINIO_SECRET_KEY:-}" ]; then
  read -rsp "Enter MinIO Secret Key: " MINIO_SECRET_KEY
  echo ""
fi

if [ -z "${MINIO_SECRET_KEY}" ]; then
  echo "ERROR: MinIO Secret Key cannot be empty."
  exit 1
fi

cat > "$SCRIPT_DIR/minio-backup-secret.yaml" <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: minio-backup-secret
  namespace: postgresql
type: Opaque
stringData:
  ACCESS_KEY_ID: "${MINIO_ACCESS_KEY}"
  ACCESS_SECRET_KEY: "${MINIO_SECRET_KEY}"
EOF

$KUBECTL apply -f "$SCRIPT_DIR/minio-backup-secret.yaml"

echo ""

############################################
# PostgreSQL Cluster
############################################

echo "Creating PostgreSQL Cluster..."

$KUBECTL apply -f "$SCRIPT_DIR/cluster.yaml"

echo ""

############################################
# Wait Cluster
############################################

echo "Waiting for PostgreSQL Cluster..."

$KUBECTL wait \
  cluster/shopixy-postgres \
  -n postgresql \
  --for=condition=Ready \
  --timeout=900s

echo ""

############################################
# PgBouncer
############################################

echo "Creating PgBouncer..."

$KUBECTL apply -f "$SCRIPT_DIR/pgbouncer.yaml"

echo ""

echo "Waiting for PgBouncer..."

# Poll until at least one PgBouncer pod exists before running kubectl wait,
# because kubectl wait errors immediately on "no matching resources found".
PGBOUNCER_READY=false
for i in $(seq 1 36); do
  POD_COUNT=$($KUBECTL get pods \
    -l cnpg.io/poolerName=shopixy-pgbouncer \
    -n postgresql \
    --no-headers 2>/dev/null | wc -l | tr -d ' ')
  if [ "${POD_COUNT}" -gt 0 ]; then
    $KUBECTL wait pod \
      -l cnpg.io/poolerName=shopixy-pgbouncer \
      -n postgresql \
      --for=condition=Ready \
      --timeout=120s && PGBOUNCER_READY=true && break
  fi
  echo "  PgBouncer pods not yet scheduled, retrying in 5s... (${i}/36)"
  sleep 5
done

if [ "$PGBOUNCER_READY" = "false" ]; then
  echo "WARNING: PgBouncer did not become ready within timeout, continuing..."
fi

echo ""

############################################
# Scheduled Backup
############################################

echo "Creating Scheduled Backup..."

cat > "$SCRIPT_DIR/scheduled-backup.yaml" <<EOF
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: shopixy-postgres-scheduled
  namespace: postgresql
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: shopixy-postgres
  method: barmanObjectStore
  immediate: false
EOF

$KUBECTL apply -f "$SCRIPT_DIR/scheduled-backup.yaml"

echo ""

############################################
# First Backup Validation
############################################

echo "Creating First Backup..."

cat > "$SCRIPT_DIR/first-backup.yaml" <<EOF
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: first-real-backup
  namespace: postgresql
spec:
  cluster:
    name: shopixy-postgres
  method: barmanObjectStore
EOF

$KUBECTL apply -f "$SCRIPT_DIR/first-backup.yaml"

echo ""

echo "Waiting For Backup Completion..."

BACKUP_DONE=false

for i in $(seq 1 180); do
  PHASE=$($KUBECTL get backup first-real-backup \
    -n postgresql \
    -o jsonpath='{.status.phase}' 2>/dev/null || true)

  if [ "$PHASE" = "completed" ]; then
    echo "Backup Completed Successfully"
    BACKUP_DONE=true
    break
  fi

  if [ "$PHASE" = "failed" ]; then
    echo "ERROR: Backup Failed"
    exit 1
  fi

  sleep 10
done

if [ "$BACKUP_DONE" = "false" ]; then
  echo "ERROR: Backup did not complete within timeout (30 minutes)"
  exit 1
fi

############################################
# WAL Validation
############################################

echo ""
echo "Validating WAL Archiving..."

PRIMARY=$($KUBECTL get cluster shopixy-postgres \
  -n postgresql \
  -o jsonpath='{.status.currentPrimary}')

if [ -z "$PRIMARY" ]; then
  echo "ERROR: Unable to determine PostgreSQL primary node"
  exit 1
fi

echo "Primary Node: $PRIMARY"

############################################
# Archive Count Before
############################################

BEFORE_ARCHIVE=$($KUBECTL exec \
  -n postgresql \
  "$PRIMARY" \
  -- psql -U postgres -At -c \
  "SELECT archived_count FROM pg_stat_archiver;")

BEFORE_ARCHIVE=$(echo "$BEFORE_ARCHIVE" | tr -d ' \t\r\n')
echo "Archive Count Before: $BEFORE_ARCHIVE"

############################################
# Generate WAL Activity
############################################

$KUBECTL exec \
  -n postgresql \
  "$PRIMARY" \
  -- psql -U postgres -d shopixy -c "
CREATE TABLE IF NOT EXISTS bootstrap_wal_test(
  id serial primary key,
  created_at timestamp default now()
);
INSERT INTO bootstrap_wal_test DEFAULT VALUES;
CHECKPOINT;
SELECT pg_switch_wal();
"

############################################
# Wait For Archive
############################################

echo "Waiting For WAL Upload..."
sleep 60

############################################
# Archive Count After
############################################

AFTER_ARCHIVE=$($KUBECTL exec \
  -n postgresql \
  "$PRIMARY" \
  -- psql -U postgres -At -c \
  "SELECT archived_count FROM pg_stat_archiver;")

AFTER_ARCHIVE=$(echo "$AFTER_ARCHIVE" | tr -d ' \t\r\n')
echo "Archive Count After: $AFTER_ARCHIVE"

############################################
# Validation
############################################

if [ -z "$BEFORE_ARCHIVE" ] || [ -z "$AFTER_ARCHIVE" ]; then
  echo ""
  echo "ERROR: Unable to read pg_stat_archiver."
  exit 1
fi

if [ "$AFTER_ARCHIVE" -le "$BEFORE_ARCHIVE" ]; then
  echo ""
  echo "ERROR: WAL Archiving Validation Failed"
  echo "Archive count did not increase."
  echo "Before: $BEFORE_ARCHIVE"
  echo "After : $AFTER_ARCHIVE"
  exit 1
fi

echo "WAL Archiving Verified"
echo "Archive Count Increased: $BEFORE_ARCHIVE -> $AFTER_ARCHIVE"
echo ""

############################################
# Monitoring
############################################

echo "Adding Prometheus Label..."

if $KUBECTL get podmonitor shopixy-postgres -n postgresql >/dev/null 2>&1; then

  $KUBECTL label podmonitor \
    shopixy-postgres \
    -n postgresql \
    release=prometheus \
    --overwrite

fi

echo ""

############################################
# Final Status
############################################

echo "================================="
echo "Bootstrap Completed Successfully"
echo "================================="
echo ""

$KUBECTL get cluster         -n postgresql
echo ""

$KUBECTL get pods            -n postgresql
echo ""

$KUBECTL get svc             -n postgresql
echo ""

$KUBECTL get pooler          -n postgresql
echo ""

$KUBECTL get backup          -n postgresql
echo ""

$KUBECTL get scheduledbackup -n postgresql
echo ""
