apiVersion: v1
kind: Secret

metadata:
  name: grafana-secret
  namespace: monitoring

type: Opaque

stringData:
  admin-user: admin
  admin-password: Fadyadel2010!

  telegram-bot-token: "8568427579:AAFdyiPHQW4C41acrlOiqcBXLbzIYkDLRoI"
  telegram-chat-id: "7650427051"
