apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: rabbitmq-servicemonitor
  namespace: rabbitmq
  labels:
    release: prometheus

spec:
  namespaceSelector:
    matchNames:
      - rabbitmq

  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq

  endpoints:
    - port: prometheus
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s

      scheme: http

