apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: shopixy-app
  namespace: rabbitmq-lab

spec:
  tags: []

  importCredentialsSecret:
    name: shopixy-app-credentials

  rabbitmqClusterReference:
    name: rabbitmq
