apiVersion: v1
kind: Namespace

metadata:
  name: rabbitmq-lab

  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: rabbitmq-lab
    app.kubernetes.io/part-of: shopixy
    app.kubernetes.io/component: messaging
    environment: lab
