#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "$ROOT_DIR/lib/common.sh"

log_info "========================================="
log_info "Namespace Generator"
log_info "========================================="

for SERVICE in $(list_services)
do

    log_info "Generating namespace for: $SERVICE"

    NAMESPACE=$(service_value "$SERVICE" namespace)
    TIER=$(service_value "$SERVICE" tier)
    CRITICALITY=$(service_value "$SERVICE" criticality)
    DESCRIPTION=$(service_value "$SERVICE" description)
    BACKUP=$(service_value "$SERVICE" backupProfile)

    PROFILE_NAME=$(profile_value ".platform.profile")
    ENVIRONMENT=$(profile_value ".environment.name")

    TEMPLATE=$(template_file namespace-template.yaml)

    OUTPUT=$(generated_dir namespaces)

    OUTPUT_FILE="$OUTPUT/$SERVICE.yaml"

    cat > "$OUTPUT_FILE" <<EOF
# ==============================================================================
# AUTO-GENERATED FILE
#
# DO NOT EDIT MANUALLY.
#
# Generated by:
#   Shopixy Platform Generator
#
# Source:
#   - profiles/shopixy-production.yaml
#   - inventory/services.yaml
#   - namespaces/templates/namespace-template.yaml
# ==============================================================================
EOF

    sed \
      -e "s/{{ namespace }}/$NAMESPACE/g" \
      -e "s/{{ profile }}/$PROFILE_NAME/g" \
      -e "s/{{ environment }}/$ENVIRONMENT/g" \
      -e "s/{{ service }}/$SERVICE/g" \
      -e "s/{{ tier }}/$TIER/g" \
      -e "s/{{ criticality }}/$CRITICALITY/g" \
      -e "s/{{ description }}/$DESCRIPTION/g" \
      -e "s/{{ backup }}/$BACKUP/g" \
      "$TEMPLATE" >> "$OUTPUT_FILE"

    log_info "Generated: $OUTPUT_FILE"

done
